-- Create departments table
create table public.departments (
  id bigint generated by default as identity primary key,
  title text not null,
  role text,
  icon_url text,
  description text,
  rank integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Toggle RLS
alter table public.departments enable row level security;

-- Policy: Everyone can view
create policy "Departments are viewable by everyone."
  on public.departments for select
  using ( true );

-- Policy: Admin can insert/update/delete (assuming anon key usage for demo, specific constraints can be added)
-- Adjust these policies based on your Auth setup. If using Anon key for everything without Auth:
create policy "Enable all access for all users"
    on public.departments for all
    using (true)
    with check (true);
